In [6]:
import pandas as pd

In [7]:
hourly_station = pd.read_csv("../data/raw/tspr2025_skytrainavgalightsbrdgs_yearstationdaytypehourly.csv")

station_year = pd.read_csv("../data/raw/tspr2025_skytrain_yearstation.csv")

rolling_hour = pd.read_csv("../data/raw/tspr2025_rail_rollinghouravgpassengervol.csv")

busiest_segments = pd.read_csv("../data/raw/tspr2025_rail_busiestsegavgvol_yearlinedaytypesegtimeperiod.csv")

daily_segments = pd.read_csv("../data/raw/tspr2025_rail_avgdailypassengervol_yearsegentdaytype.csv")

line_ridership = pd.read_csv("../data/raw/tspr2025_rail_ridershipbrdgs_yearline.csv")

In [8]:
station_year.head()

,CalendarYear,StationName,AnnualStationBrdgs,AvgStationBrdgs_MF,AvgStationBrdgs_Sat,AvgStationBrdgs_SunHol
0,2023,22nd Street Station,3407157.304,10713.287730,7314.544294,5834.240069
1,2023,29th Avenue Station,2174793.588,6520.027441,5429.213608,4323.410767
2,2023,Aberdeen Station,1268781.499,3479.516228,3890.925276,3169.357270
3,2023,Braid Station,1194905.683,3821.302367,2505.905584,1858.762676
4,2023,Brentwood Town Centre Station,2120431.077,6585.061473,4911.196726,3670.612372

In [9]:
print("Hourly station:", hourly_station.shape)
print("Station year:", station_year.shape)
print("Rolling hour:", rolling_hour.shape)
print("Busiest segments:", busiest_segments.shape)
print("Daily segments:", daily_segments.shape)
print("Line ridership:", line_ridership.shape)

Hourly station: (11413, 6)
Station year: (161, 6)
Rolling hour: (86792, 12)
Busiest segments: (126, 9)
Daily segments: (990, 10)
Line ridership: (9, 6)

In [10]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    print(f"\n{name}:")
    print(df.columns.tolist())

Hourly station:
['CalendarYear', 'StationName', 'DayType', 'Hour', 'Average_Daily_Station_Alightings', 'Average_Daily_Station_Boardings']

Station year:
['CalendarYear', 'StationName', 'AnnualStationBrdgs', 'AvgStationBrdgs_MF', 'AvgStationBrdgs_Sat', 'AvgStationBrdgs_SunHol']

Rolling hour:
['TravYear', 'SegMode', 'DayType', 'Hour_24', 'Minute_15', 'FromStn_Short', 'ToStn_Short', 'FromStn_Long', 'ToStn_Long', 'Direction', 'SegID', 'AvgHrlyVol']

Busiest segments:
['TravYear', 'SegMode', 'DayType', 'TimePeriod', 'TravFromStn', 'TravToStn', 'hour_24', 'minute_15', 'AvgHrlyVol']

Daily segments:
['TravYear', 'SegMode', 'DayType', 'FromStn_Short', 'ToStn_Short', 'FromStn_Long', 'ToStn_Long', 'SegDir', 'SegID', 'AvgDailyVol']

Line ridership:
['CalendarYear', 'Mode', 'Annual_Boardings', 'AvgBrdgs_MF', 'AvgBrdgs_Sat', 'AvgBrdgs_SunHol']

In [11]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    print(f"\n{name}:")
    print(df.dtypes)

Hourly station:
CalendarYear                        int64
StationName                           str
DayType                               str
Hour                                  str
Average_Daily_Station_Alightings    int64
Average_Daily_Station_Boardings     int64
dtype: object

Station year:
CalendarYear                int64
StationName                   str
AnnualStationBrdgs        float64
AvgStationBrdgs_MF        float64
AvgStationBrdgs_Sat       float64
AvgStationBrdgs_SunHol    float64
dtype: object

Rolling hour:
TravYear           int64
SegMode              str
DayType              str
Hour_24            int64
Minute_15          int64
FromStn_Short        str
ToStn_Short          str
FromStn_Long         str
ToStn_Long           str
Direction            str
SegID              int64
AvgHrlyVol       float64
dtype: object

Busiest segments:
TravYear         int64
SegMode            str
DayType            str
TimePeriod         str
TravFromStn        str
TravToStn          str
hour_24          int64
minute_15        int64
AvgHrlyVol     float64
dtype: object

Daily segments:
TravYear           int64
SegMode              str
DayType              str
FromStn_Short        str
ToStn_Short          str
FromStn_Long         str
ToStn_Long           str
SegDir               str
SegID              int64
AvgDailyVol      float64
dtype: object

Line ridership:
CalendarYear          int64
Mode                    str
Annual_Boardings    float64
AvgBrdgs_MF         float64
AvgBrdgs_Sat        float64
AvgBrdgs_SunHol     float64
dtype: object

In [12]:
hourly_station["Hour"].unique()

<StringArray>
[     '3:00 to 4:00 PM',      '3:00 to 4:00 AM',      '2:00 to 3:00 PM',
      '2:00 to 3:00 AM',     '12:00 to 1:00 PM',     '12:00 to 1:00 AM',
 '11:00 PM to 12:00 AM', '11:00 AM to 12:00 PM',    '10:00 to 11:00 PM',
    '10:00 to 11:00 AM',      '1:00 to 2:00 PM',      '1:00 to 2:00 AM',
     '9:00 to 10:00 PM',     '9:00 to 10:00 AM',      '4:00 to 5:00 AM',
      '4:00 to 5:00 PM',      '5:00 to 6:00 AM',      '5:00 to 6:00 PM',
      '6:00 to 7:00 AM',      '6:00 to 7:00 PM',      '7:00 to 8:00 AM',
      '7:00 to 8:00 PM',      '8:00 to 9:00 AM',      '8:00 to 9:00 PM']
Length: 24, dtype: str

In [13]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    print(f"\n{name}:")
    print(df.isnull().sum())

Hourly station:
CalendarYear                        0
StationName                         0
DayType                             0
Hour                                0
Average_Daily_Station_Alightings    0
Average_Daily_Station_Boardings     0
dtype: int64

Station year:
CalendarYear              0
StationName               0
AnnualStationBrdgs        0
AvgStationBrdgs_MF        0
AvgStationBrdgs_Sat       0
AvgStationBrdgs_SunHol    0
dtype: int64

Rolling hour:
TravYear            0
SegMode             0
DayType             0
Hour_24             0
Minute_15           0
FromStn_Short    1570
ToStn_Short      1572
FromStn_Long        0
ToStn_Long          0
Direction           0
SegID               0
AvgHrlyVol          0
dtype: int64

Busiest segments:
TravYear       0
SegMode        0
DayType        0
TimePeriod     0
TravFromStn    0
TravToStn      0
hour_24        0
minute_15      0
AvgHrlyVol     0
dtype: int64

Daily segments:
TravYear          0
SegMode           0
DayType           0
FromStn_Short    18
ToStn_Short      18
FromStn_Long      0
ToStn_Long        0
SegDir            0
SegID             0
AvgDailyVol       0
dtype: int64

Line ridership:
CalendarYear        0
Mode                0
Annual_Boardings    0
AvgBrdgs_MF         0
AvgBrdgs_Sat        3
AvgBrdgs_SunHol     3
dtype: int64

In [15]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    print(name, df.duplicated().sum())

Hourly station 0
Station year 0
Rolling hour 0
Busiest segments 0
Daily segments 0
Line ridership 0

In [16]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    year_col = "CalendarYear" if "CalendarYear" in df.columns else "TravYear"
    print(name, sorted(df[year_col].unique()))

Hourly station [np.int64(2023), np.int64(2024), np.int64(2025)]
Station year [np.int64(2023), np.int64(2024), np.int64(2025)]
Rolling hour [np.int64(2023), np.int64(2024), np.int64(2025)]
Busiest segments [np.int64(2023), np.int64(2024), np.int64(2025)]
Daily segments [np.int64(2023), np.int64(2024), np.int64(2025)]
Line ridership [np.int64(2023), np.int64(2024), np.int64(2025)]

In [17]:
for name, df in {
    "Hourly station": hourly_station,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments
}.items():
    print(name, df["DayType"].unique())

Hourly station <StringArray>
['Sun/Hol', 'Sat', 'MF']
Length: 3, dtype: str
Rolling hour <StringArray>
['MF', 'Sat', 'Sun/Hol']
Length: 3, dtype: str
Busiest segments <StringArray>
['MF', 'Sat', 'Sun/Hol']
Length: 3, dtype: str
Daily segments <StringArray>
['MF', 'Sat', 'Sun/Hol']
Length: 3, dtype: str

In [18]:
print("Rolling hour:", rolling_hour["SegMode"].unique())
print("Daily segments:", daily_segments["SegMode"].unique())

Rolling hour: <StringArray>
['C', 'M']
Length: 2, dtype: str
Daily segments: <StringArray>
['C', 'M']
Length: 2, dtype: str

In [19]:
line_ridership["Mode"].unique()

<StringArray>
['Canada Line', 'Expo/Millennium Line', 'West Coast Express']
Length: 3, dtype: str

In [20]:
station_year.groupby("CalendarYear")["StationName"].nunique()

CalendarYear
2023    53
2024    54
2025    54
Name: StationName, dtype: int64

In [21]:
stations_2023 = set(
    station_year.loc[station_year["CalendarYear"] == 2023, "StationName"]
)

stations_2024 = set(
    station_year.loc[station_year["CalendarYear"] == 2024, "StationName"]
)

stations_2024 - stations_2023

{'Capstan Station'}

In [22]:
for name, df in {
    "Hourly station": hourly_station,
    "Station year": station_year,
    "Rolling hour": rolling_hour,
    "Busiest segments": busiest_segments,
    "Daily segments": daily_segments,
    "Line ridership": line_ridership
}.items():
    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print(f"\n{name}:")
    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing)

Hourly station:
No missing values

Station year:
No missing values

Rolling hour:
FromStn_Short    1570
ToStn_Short      1572
dtype: int64

Busiest segments:
No missing values

Daily segments:
FromStn_Short    18
ToStn_Short      18
dtype: int64

Line ridership:
AvgBrdgs_Sat       3
AvgBrdgs_SunHol    3
dtype: int64

In [23]:
rolling_hour[
    rolling_hour["FromStn_Short"].isnull()
][
    ["FromStn_Short", "FromStn_Long", "ToStn_Short", "ToStn_Long"]
].drop_duplicates()

     FromStn_Short FromStn_Long ToStn_Short               ToStn_Long
8198           NaN  Nanaimo Stn          BW  Commercial-Broadway Stn

In [24]:
rolling_hour[
    rolling_hour["ToStn_Short"].isnull()
][
    ["FromStn_Short", "FromStn_Long", "ToStn_Short", "ToStn_Long"]
].drop_duplicates()

     FromStn_Short FromStn_Long ToStn_Short   ToStn_Long
8222            TN  29th Av Stn         NaN  Nanaimo Stn

In [25]:
daily_segments[
    daily_segments["FromStn_Short"].isnull() |
    daily_segments["ToStn_Short"].isnull()
][
    ["FromStn_Short", "FromStn_Long", "ToStn_Short", "ToStn_Long"]
].drop_duplicates()

    FromStn_Short FromStn_Long ToStn_Short               ToStn_Long
140           NaN  Nanaimo Stn          BW  Commercial-Broadway Stn
164            TN  29th Av Stn         NaN              Nanaimo Stn

In [26]:
line_ridership[
    line_ridership["AvgBrdgs_Sat"].isnull() |
    line_ridership["AvgBrdgs_SunHol"].isnull()
]

,CalendarYear,Mode,Annual_Boardings,AvgBrdgs_MF,AvgBrdgs_Sat,AvgBrdgs_SunHol
2,2023,West Coast Express,1304441.0,5251.060729,NaN,NaN
5,2024,West Coast Express,1559123.0,6225.919679,NaN,NaN
8,2025,West Coast Express,1734067.0,6946.237903,NaN,NaN

In [27]:
print("Hourly alightings:", (hourly_station["Average_Daily_Station_Alightings"] < 0).sum())
print("Hourly boardings:", (hourly_station["Average_Daily_Station_Boardings"] < 0).sum())

print("Annual station boardings:", (station_year["AnnualStationBrdgs"] < 0).sum())

print("Rolling hour volume:", (rolling_hour["AvgHrlyVol"] < 0).sum())

print("Busiest segment volume:", (busiest_segments["AvgHrlyVol"] < 0).sum())

print("Daily segment volume:", (daily_segments["AvgDailyVol"] < 0).sum())

print("Annual line boardings:", (line_ridership["Annual_Boardings"] < 0).sum())

Hourly alightings: 0
Hourly boardings: 0
Annual station boardings: 0
Rolling hour volume: 0
Busiest segment volume: 0
Daily segment volume: 0
Annual line boardings: 0